version: '3'
services:
  client:
    image: huyhieu9301/complex-client
  api:
    image: huyhieu9301/complex-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: huyhieu9301/complex-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: huyhieu9301/complex-nginx
    ports:
      - '80:80'
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest

volumes:
  pgdata:
